### ISSUE TITLE
Breadwallet mentioned on Import Paper Wallet

### ISSUE THREAD

**Issue by ChillingSilence** [Racecraft/digibytewallet-android#14]
When importing a paper wallet, Breadwallet is mentioned.
If this is an image, does this subsequently also affect all translations?

![screenshot_2018-02-18-09-07-20-466_nl netfur digibyte](https://user-images.githubusercontent.com/162461/36345211-734425f8-148b-11e8-931c-6326e727a389.png)

**Comment by FoamyGuy** [comment]
It is an image. Yes it would affect all languages unless we also provide a different image for each. It'll be easier to support if we cut the text out of the image and add it in the layout. I'll work on separating them and changing it to DigiByte.
