### ISSUE TITLE
Syncing card scrolls tx history to the top

### ISSUE THREAD

**Issue by ChillingSilence** [Racecraft/digibytewallet-android#6]
When scrolling down a list of transactions on the main Android Wallet screen, whenever the "syncing" occurs as it finds a new block, it scrolls to the top, making it incredibly difficult to see a transaction at the bottom of a list of a dozen-odd
Video showing this is zipped up (Github won't allow the MP4 upload directly)

[Screenrecorder-2018-02-15-12-42-15-927.zip](https://github.com/Racecraft/digibytewallet-android/files/1726124/Screenrecorder-2018-02-15-12-42-15-927.zip)

Expected behavior: Don't have the "Syncing" card steal the focus and scroll you to the top

**Comment by nseidm1** [comment]
With the new static top location of the syncing view structure, this issue is happily resolved. Cheers my man.
