### ISSUE TITLE
Progress of transactions doesn't seem to update during syncing

### ISSUE THREAD

**Issue by ChillingSilence** [Racecraft/digibytewallet-android#7]
When syncing a wallet (Say, when restoring from backup), transactions come into the list
These transactions don't update their status correctly to indicate how many confirms they have:
![screenshot_2018-02-15-13-26-09-961_io digibyte](https://user-images.githubusercontent.com/162461/36236349-87081122-125a-11e8-9bd1-7c23807dc994.png)
First transaction showing sync'd to 2PM, unconfirmed
Again with another couple of hours worth of syncing:
![screenshot_2018-02-15-13-26-18-220_io digibyte](https://user-images.githubusercontent.com/162461/36236361-92fb0160-125a-11e8-922f-8f3a143aa392.png)
Still showing "Receiving - 0%".

Closing the app and restoring it shows the correct status as "Complete".
There's no way there were no blocks for an hour, so after 2 hours, ANY pending transaction should be complete

Expected behavior: The app should update the card to show if the transaction has more than 6 blocks after it and is deemed confirmed / complete.

**Comment by nseidm1** [comment]
With the current design of the transaction list this is highly likely to be resolved. The entire transaction adapter is fresh and so clean clean. If any issues still persist I'm happy to knock them out. Cheers.
